name: Dependabot auto-approve
on: pull_request

permissions:
  pull-requests: write

env:
  PR_URL: ${{github.event.pull_request.html_url}}
  GH_TOKEN: ${{secrets.GITHUB_TOKEN}}
  PR_NUM: ${{github.event.pull_request.number}}
  PR_TITLE: ${{github.event.pull_request.title}}

jobs:
  dependabot:
    runs-on: ubuntu-latest
    if: github.actor == 'dependabot[bot]'
    steps:
    
      - name: Dependabot metadata
        id: metadata
        uses: dependabot/fetch-metadata@v2
        with:
          github-token: "${{ secrets.GITHUB_TOKEN }}"
          
      - name: Approve a PR "$PR_TITLE"
        run: gh pr review --approve "$PR_URL"
        
      - name: Merge a PR:$PR_NUM  "$PR_TITLE"
        run: gh pr merge --auto --squash --merge "$PR_URL"
        
