on: push
jobs:
  build:
    name: Download composer packages
    runs-on: ubuntu-latest
    steps:
      - name: Checkout The PHP API using Apache-server
        uses: actions/checkout@v4
      - name: Composer (PHP action)
        uses: php-actions/composer@v6
        with:
          php_version: 8.3
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: composer-cache
        #   path: vendor
          path: .

  api:
    name: Build API
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v3
        with:
          name: composer-cache
          path: ${{ github.workspace }}
          merge_multiple: true
      - name: Build API
        run: |
          docker build . -t php-api:${{ github.run_number }}
