on: push
jobs:
  build:
    name: Download composer packages
    runs-on: ubuntu-latest
    steps:
      - name: Checkout The PHP API using Apache-server
        uses: actions/checkout@v4
      - name: Composer (PHP action)
        uses: php-actions/composer@v6
        with:
          php_version: 8.3
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: composer-cache
          path: .
      - name: Zip archive
        uses: TheDoctor0/zip-release@0.7.6
        with:
          filename: composer-cache
          path: .

  api:
    name: Build API
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          name: composer-cache
          path: .
      - name: Build API
        run: |
          docker build . -t php-api:${{ github.run_number }}
      - name: Login to Docker Hub
        uses: docker/login-action@v3.0.0
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          push: true
          context: .
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/mariageapi:latest
