on: push
jobs:
  build:
    name: Build the PHP API using APache-server
    runs-on: ubuntu-latest
    steps:
      - name: Checkout The PHP API using APache-server
        uses: actions/checkout@v4
      - name: Composer (PHP action)
        uses: php-actions/composer@v6
        with:
            php_version: 8.3
      - name: Build API
        run: |
          docker build . -t php-api:${{ github.run_number }}
