on: push
jobs:
    build:
        name: Build the PHP API using APache-server
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - name: Build API
              run: |
                  docker build . -t php-api:1.0